import { useState } from 'react'
import { useProject } from './ProjectLayout'
import { useStore, type GeneratedReport } from '../store/useStore'
import { Card, CardHead, Button, Chip } from '../components/ui/primitives'
import { aed } from '../lib/format'
import { currentPhase, nextMilestone, calLabel, spentPct } from '../lib/metrics'
import { buildSimplePdf, buildCsv, triggerDownload } from '../lib/download'
import type { Project } from '../data/types'

const SECTIONS = ['Health & status', 'Budget breakdown', 'Milestones', 'Risk register', 'Team & resources', 'Stakeholders'] as const
type Section = (typeof SECTIONS)[number]

function slug(p: Project) {
  return p.name.replace(/[^a-zA-Z0-9]+/g, '').slice(0, 24)
}

function buildLines(p: Project, params: Section[]): string[] {
  const lines: string[] = [p.name, `${p.department} · ${p.contractType}`, p.location ? `Location: ${p.location}` : '', '']
  if (params.includes('Health & status')) {
    const ph = currentPhase(p)
    const next = nextMilestone(p)
    lines.push('HEALTH & STATUS', `Health: ${p.healthNote}`, `Current phase: ${ph.name} (${ph.progressPct}%)`, `Overall completion: ${p.overallProgress}%`,
      next ? `Next milestone: ${next.milestone.name} — ${calLabel(p, next.milestone.month)} (${next.days} days)` : 'No upcoming milestones', '')
  }
  if (params.includes('Budget breakdown')) {
    lines.push('BUDGET', `Spent: ${aed(p.spentBudget)} of ${aed(p.totalBudget)} (${spentPct(p).toFixed(1)}%)`,
      ...p.budgetLines.map((b) => `  - ${b.phase}: ${aed(b.allocated)}`), '')
  }
  if (params.includes('Milestones')) {
    lines.push('MILESTONES', ...p.milestones.map((m) => `  - ${m.name}: ${calLabel(p, m.month)} [${m.state.replace('_', ' ')}]`), '')
  }
  if (params.includes('Risk register')) {
    lines.push('RISK REGISTER', ...(p.risks.length ? p.risks.map((r) => `  - ${r.risk} (P:${r.probability}/I:${r.impact}) — ${r.mitigation}`) : ['  None logged']), '')
  }
  if (params.includes('Team & resources')) {
    lines.push('TEAM', ...p.team.map((t) => `  - ${t.name} — ${t.role} (${t.access})`), '')
  }
  if (params.includes('Stakeholders')) {
    lines.push('STAKEHOLDERS', ...p.internalStakeholders.map((s) => `  - ${s.name}, ${s.title}`), ...p.externalPartners.map((s) => `  - ${s.org} — ${s.role}`), '')
  }
  lines.push(`Generated by Softteco Project Administration · ${DEMO_DATE}`)
  return lines.filter((l) => l !== undefined)
}

function buildRows(p: Project, params: Section[]): (string | number)[][] {
  const rows: (string | number)[][] = [['Project', p.name], ['Department', p.department], []]
  if (params.includes('Health & status')) rows.push(['Section', 'Health & status'], ['Health', p.healthNote], ['Completion', `${p.overallProgress}%`], [])
  if (params.includes('Budget breakdown')) { rows.push(['Phase', 'Allocated (AED)']); p.budgetLines.forEach((b) => rows.push([b.phase, b.allocated])); rows.push(['Total', p.totalBudget], []) }
  if (params.includes('Milestones')) { rows.push(['Milestone', 'Date', 'State']); p.milestones.forEach((m) => rows.push([m.name, calLabel(p, m.month), m.state])); rows.push([]) }
  if (params.includes('Risk register')) { rows.push(['Risk', 'Probability', 'Impact']); p.risks.forEach((r) => rows.push([r.risk, r.probability, r.impact])); rows.push([]) }
  if (params.includes('Team & resources')) { rows.push(['Member', 'Role', 'Access']); p.team.forEach((t) => rows.push([t.name, t.role, t.access])); rows.push([]) }
  if (params.includes('Stakeholders')) { rows.push(['Stakeholder', 'Detail']); p.internalStakeholders.forEach((s) => rows.push([s.name, s.title])); p.externalPartners.forEach((s) => rows.push([s.org, s.role])) }
  return rows
}

const DEMO_DATE = '20 Feb 2026'

function download(p: Project, params: Section[], format: 'PDF' | 'CSV', name: string) {
  if (format === 'PDF') triggerDownload(buildSimplePdf(name, buildLines(p, params)), `${slug(p)}_${name.replace(/\s+/g, '')}.pdf`)
  else triggerDownload(buildCsv(buildRows(p, params)), `${slug(p)}_${name.replace(/\s+/g, '')}.csv`)
}

export function ReportsPage() {
  const p = useProject()
  const allReports = useStore((s) => s.generatedReports)
  const reports = allReports.filter((r) => r.projectId === p.id)
  const addReport = useStore((s) => s.addGeneratedReport)

  const [selected, setSelected] = useState<Section[]>(['Health & status', 'Budget breakdown', 'Milestones'])
  const [format, setFormat] = useState<'PDF' | 'CSV'>('PDF')
  const [name, setName] = useState('Project status report')

  function toggle(sec: Section) {
    setSelected((cur) => (cur.includes(sec) ? cur.filter((s) => s !== sec) : [...cur, sec]))
  }
  function generate() {
    if (!selected.length) return
    download(p, selected, format, name.trim() || 'Project report')
    addReport({
      id: `r-${Date.now()}`,
      projectId: p.id,
      name: name.trim() || 'Project report',
      dateLabel: DEMO_DATE,
      params: [...selected],
      format,
    })
  }

  return (
    <div className="grid gap-5">
      <p className="text-sm text-muted">Pick the parameters you want, generate a branded file, download it to share — every report is also kept below.</p>

      {/* Builder */}
      <Card className="p-5">
        <CardHead title="Build a report" />
        <div className="grid gap-2.5 px-0 pt-2 sm:grid-cols-2 lg:grid-cols-3">
          {SECTIONS.map((sec) => {
            const on = selected.includes(sec)
            return (
              <button key={sec} onClick={() => toggle(sec)}
                className={`flex items-center gap-2 rounded-xl border px-3 py-2.5 text-left text-sm transition ${on ? 'border-navy bg-[#f7f8fb] font-medium text-ink' : 'border-line text-[#475467] hover:bg-[#f3f5f9]'}`}>
                <span className={`grid h-4 w-4 shrink-0 place-items-center rounded border text-[10px] leading-none ${on ? 'border-navy bg-navy text-white' : 'border-[#c2c7d2]'}`}>{on ? '✓' : ''}</span>
                {sec}
              </button>
            )
          })}
        </div>

        <div className="mt-4 flex flex-wrap items-end gap-3">
          <label className="grid gap-1">
            <span className="text-xs text-muted">Report name</span>
            <input value={name} onChange={(e) => setName(e.target.value)} className="w-64 rounded-xl border border-line px-3 py-2 text-sm outline-none focus:border-navy" />
          </label>
          <label className="grid gap-1">
            <span className="text-xs text-muted">Format</span>
            <div className="flex rounded-xl border border-line bg-card p-1">
              {(['PDF', 'CSV'] as const).map((f) => (
                <button key={f} onClick={() => setFormat(f)} className={`rounded-lg px-4 py-1.5 text-sm font-medium transition ${format === f ? 'bg-navy text-white' : 'text-muted hover:text-ink'}`}>{f}</button>
              ))}
            </div>
          </label>
          <Button onClick={generate} disabled={!selected.length}>⬇ Generate & download</Button>
        </div>
        <p className="mt-2 text-xs text-muted">{selected.length} section{selected.length === 1 ? '' : 's'} selected · PDF is branded Softteco + RAK Municipality · CSV opens in Excel.</p>
      </Card>

      {/* History */}
      <Card className="overflow-hidden">
        <CardHead title={`Generated reports (${reports.length})`} />
        {reports.length === 0 ? (
          <p className="px-5 pb-5 text-sm text-muted">No reports yet — build one above and it will be kept here to re-download or forward.</p>
        ) : (
          <div className="px-5 pb-5">
            {reports.map((r: GeneratedReport) => (
              <div key={r.id} className="flex flex-wrap items-center justify-between gap-3 border-b border-line py-3 last:border-0">
                <div className="min-w-0">
                  <div className="flex items-center gap-2">
                    <span className={`grid h-7 w-9 place-items-center rounded-md text-[11px] font-bold text-white ${r.format === 'PDF' ? 'bg-red' : 'bg-green'}`}>{r.format}</span>
                    <span className="text-sm font-semibold text-ink">{r.name}</span>
                    <span className="text-xs text-muted">· {r.dateLabel}</span>
                  </div>
                  <div className="mt-1 flex flex-wrap gap-1">
                    {r.params.map((p2) => <Chip key={p2}>{p2}</Chip>)}
                  </div>
                </div>
                <Button variant="soft" onClick={() => download(p, r.params as Section[], r.format, r.name)}>⬇ Download again</Button>
              </div>
            ))}
          </div>
        )}
      </Card>
    </div>
  )
}
