import { useProject } from './ProjectLayout'
import { Card, Button } from '../components/ui/primitives'
import { aed, monthLabel } from '../lib/format'
import { currentPhase, nextMilestone, budgetVariance } from '../lib/metrics'
import { buildSimplePdf, buildCsv, triggerDownload, openHtmlPreview } from '../lib/download'
import type { Project } from '../data/types'

function slug(p: Project) {
  return p.name.replace(/[^a-zA-Z0-9]+/g, '').slice(0, 24)
}

function statusLines(p: Project): string[] {
  const phase = currentPhase(p)
  const next = nextMilestone(p)
  const v = budgetVariance(p)
  return [
    `Project: ${p.name}`,
    `Department: ${p.department}`,
    `Contract: ${p.contractType}`,
    '',
    `Overall health: ${p.healthNote}`,
    `Current phase: ${phase.name} (${phase.progressPct}%)`,
    `Overall completion: ${p.overallProgress}%`,
    '',
    `Budget: ${aed(p.spentBudget)} spent of ${aed(p.totalBudget)}`,
    `Variance: under budget by ${aed(v.underBy)}`,
    '',
    next ? `Next milestone: ${next.milestone.name} (${monthLabel(next.milestone.month, p.startYear)}, ${next.days} days)` : '',
    `Open issues: ${p.issues.length}`,
    `Top risk: ${p.risks[0]?.risk ?? '-'}`,
    '',
    `Generated by Softteco Project Administration · ${'20 Feb 2026'}`,
  ].filter((l) => l !== undefined)
}

function milestoneLines(p: Project): string[] {
  return [
    `Project: ${p.name}`,
    'Milestone progress report',
    '',
    ...p.milestones.map(
      (m) => `- ${m.name}: ${monthLabel(m.month, p.startYear)} | ${m.rag.toUpperCase()} | ${m.state.replace('_', ' ')}`,
    ),
    '',
    `Generated by Softteco · RAK Municipality`,
  ]
}

function budgetCsv(p: Project): (string | number)[][] {
  return [
    ['Phase', 'Allocated (AED)', 'Category'],
    ...p.budgetLines.map((b) => [b.phase, b.allocated, b.category]),
    ['Total', p.totalBudget, ''],
    [],
    ['Spent to date', p.spentBudget, ''],
  ]
}

function resourceCsv(p: Project): (string | number)[][] {
  const header = ['Team member', 'Role', ...p.phases.map((ph) => ph.name)]
  return [
    header,
    ...p.team.map((t) => [t.name, t.role, ...t.fteByPhase.map((f) => `${f} FTE`)]),
  ]
}

function previewHtml(p: Project): string {
  const phase = currentPhase(p)
  const rows = statusLines(p)
    .map((l) => (l === '' ? '<div style="height:10px"></div>' : `<div>${l}</div>`))
    .join('')
  return `<!doctype html><html><head><meta charset="utf-8"><title>${p.name} — Status report</title>
  <style>body{font-family:Inter,system-ui,sans-serif;color:#1a2235;margin:0;background:#f0f2f5}
  .page{max-width:720px;margin:24px auto;background:#fff;border-radius:16px;padding:40px;box-shadow:0 6px 24px rgba(0,0,0,.08)}
  .brand{display:flex;justify-content:space-between;align-items:center;border-bottom:2px solid #4caf82;padding-bottom:16px;margin-bottom:24px}
  .logo{font-weight:800;font-size:20px}.logo span{color:#4caf82}
  h1{font-size:22px;margin:0 0 4px}.muted{color:#6b7280}
  .body div{padding:3px 0;font-size:14px}</style></head>
  <body><div class="page">
  <div class="brand"><div class="logo">Soft<span>teco</span></div><div class="muted">RAK Municipality</div></div>
  <h1>Project Status Report</h1>
  <div class="muted">${phase.name} · Generated 20 Feb 2026</div>
  <div class="body" style="margin-top:20px">${rows}</div>
  </div></body></html>`
}

interface ReportDef {
  title: string
  format: 'PDF' | 'XLS'
  desc: string
  onDownload: (p: Project) => void
  onPreview?: (p: Project) => void
}

const REPORTS: ReportDef[] = [
  {
    title: 'Project status report',
    format: 'PDF',
    desc: 'Full project health summary — phase, budget, risks, milestones',
    onDownload: (p) => triggerDownload(buildSimplePdf('Project Status Report', statusLines(p)), `${slug(p)}_StatusReport_Feb2026.pdf`),
    onPreview: (p) => openHtmlPreview(previewHtml(p)),
  },
  {
    title: 'Budget summary',
    format: 'XLS',
    desc: 'Planned vs actual spend by phase and category',
    onDownload: (p) => triggerDownload(buildCsv(budgetCsv(p)), `${slug(p)}_BudgetSummary_Feb2026.csv`),
  },
  {
    title: 'Milestone progress',
    format: 'PDF',
    desc: 'All milestones with status, owner, and forecast dates',
    onDownload: (p) => triggerDownload(buildSimplePdf('Milestone Progress Report', milestoneLines(p)), `${slug(p)}_Milestones_Feb2026.pdf`),
  },
  {
    title: 'Resource utilization',
    format: 'XLS',
    desc: 'Team FTE allocation and capacity by phase',
    onDownload: (p) => triggerDownload(buildCsv(resourceCsv(p)), `${slug(p)}_ResourceUtilization_Feb2026.csv`),
  },
]

export function ReportsPage() {
  const p = useProject()
  return (
    <div>
      <h2 className="text-lg font-bold text-ink">Reports</h2>
      <p className="text-sm text-muted">One-click, branded reports — ready to share with leadership or the PPP consortium.</p>
      <div className="mt-5 grid gap-4 sm:grid-cols-2">
        {REPORTS.map((r) => (
          <Card key={r.title} className="flex flex-col p-5">
            <div className="flex items-start gap-3">
              <div className={`grid h-11 w-11 place-items-center rounded-xl text-sm font-bold text-white ${r.format === 'PDF' ? 'bg-red' : 'bg-green'}`}>
                {r.format}
              </div>
              <div className="flex-1">
                <h3 className="text-sm font-bold text-ink">{r.title}</h3>
                <p className="mt-0.5 text-xs text-muted">{r.desc}</p>
                <p className="mt-1 text-[11px] text-muted">Last generated: Today</p>
              </div>
            </div>
            <div className="mt-4 flex gap-2">
              {r.onPreview && (
                <Button variant="soft" onClick={() => r.onPreview!(p)}>
                  Preview
                </Button>
              )}
              <Button onClick={() => r.onDownload(p)}>⬇ Download</Button>
            </div>
          </Card>
        ))}
      </div>
      <p className="mt-4 text-xs text-muted">PDF reports are branded with Softteco + RAK Municipality. XLS exports open in Excel.</p>
    </div>
  )
}
